name: fripo
description: The Fripo App for mobile.

publish_to: 'none'
version: 0.2.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  dartz:
  get_it:
  provider:

  # Repository
  photo_manager:
  crop_your_image: 

  # Firebase
  firebase_core:
  firebase_auth:
  firebase_database:
  firebase_storage:
  cloud_functions:

  # View
  cached_network_image:
  google_mobile_ads:
  webview_flutter:
  loading_animation_widget:
  app_review:
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_native_splash:
  flutter_launcher_icons:

flutter:

  uses-material-design: true

  assets:
    - assets/image/fripo_touch.png
    - assets/image/bubble.png
    - assets/image/logo.png
    - assets/image/
    - assets/json/theme_list.json
    - assets/protected/admob.json

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/font/NotoSansJP-Black.otf
          weight: 900
        - asset: assets/font/NotoSansJP-Bold.otf
          weight: 700
        - asset: assets/font/NotoSansJP-Medium.otf
          weight: 500
        - asset: assets/font/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/font/NotoSansJP-Light.otf
          weight: 300
        - asset: assets/font/NotoSansJP-Thin.otf
          weight: 100
    - family: BlackHanSans
      fonts:
        - asset: assets/font/BlackHanSans-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/image/icon.jpg'
  adaptive_icon_foreground: 'assets/image/icon_foreground.png'
  adaptive_icon_background: '#ff7d30'

flutter_native_splash:
  color: '#ff7d30'
  image: 'assets/image/splash_image.png'
  android_12:
    icon_background_color: '#ff7d30'
    image: 'assets/image/splash_image_android_12.png'
